name: CICD
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4.1.2
      - name: step 2
        run: ls -l
        
