#My First Workflow

name: workflow1
on:
  push:
  workflow_dispatch:
env:
  greetings: "Good Morning"
  name: "Chai Fong"
  lastname: "Khor"
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      greetings: "hello"
    steps:
      - name: step1
        run: |
          echo "$greetings! from $name. It run this workflow under repo ${{GITHUB1.REPOSITORY}} and it is running on OS ${{RUNNER.OS}}"
          echo "Application name is ${{vars.APP_NAME}} and password is ${{secrets.SERVER_PASSWORD}}"
          echo The value of SERVER_PASSWORD secret variable is: ${{secrets.SERVER_PASSWORD}} | sed 's/./& /g'
          echo "${{vars.app_name}} is hosted on ${{vars.SERVER_NAME}}"
          sleep 5
        env:
          name: cf
      - name: step2 for testing
        run: |
          cat /etc/os-release 
          sleep 5
          hostname
          touch /tmp/cf
          echo "$greetings! from $name"
    ## Name us not important in a step
      - run: uname -a
      
  test:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    env:
      greetings: "hello"
    steps:
      - name: step1
        run: |
          echo "$greetings! from $name. It run this workflow under repo ${{GITHUB.REPOSITORY}} and it is running on OS ${{RUNNER.OS}}"
          sleep 5
  stage:
    runs-on: ubuntu-latest
    environment: prod
    needs: test
    env:
      greetings: "hello"
    steps:
      - name: step1
        run: |
          echo "$greetings! from $name. It run this workflow under repo ${{GITHUB.REPOSITORY}} and it is running on OS ${{RUNNER.OS}}"
          sleep 5
          
      
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: test
    env:
      lastname: "khor"
    steps:
      - name: step1
        run: |
          echo "$greetings! from $name $lastname"
          echo "${{vars.app_name}} is hosted on ${{vars.SERVER_NAME}}"
        env:
          name: cf
      - name: step2 for testing
        run: |
          cat /etc/os-release 
          hostname
          touch /tmp/cf
          echo "$greetings! from $name"
      
  
