#My First Workflow

name: workflow1
on:
  push:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: step1
        run: |
          echo "Hello from $name"
          env:
            name: cf
      - name: step2 for testing
        run: |
          cat /etc/os-release 
          hostname
          touch /tmp/cf

    ## Name us not important in a step
      - run: uname -a

      
  
