#My First Workflow

name: workflow1
on: 
  push:
    branches:
      - main


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello from CF"
      - name: step2
        run: cat/etc/os-release 
    ## Name us not important in a step
      - run: uname -a
  
