#My First Workflow

name: workflow1
on:
  push:
  workflow_dispatch:
env:
  greetings: "Good Morning"
  name: "Chai Fong"
  lastname: "Khor"
  
jobs:
  build:
    runs-on: ubuntu-latest
    env: dev
      greetings: "hello"
    steps:
      - name: step1
        run: |
          echo "$greetings! from $name. It run this workflow under repo ${{GITHUB.REPOSITORY}} and it is running on OS ${{RUNNER.OS}}"
          echo "${{vars.app_name}} is hosted on ${{vars.SERVER_NAME}}"
          sleep 5
        env:
          name: cf
      - name: step2 for testing
        run: |
          cat /etc/os-release 
          sleep 5
          hostname
          touch /tmp/cf
          echo "$greetings! from $name"
    ## Name us not important in a step
      - run: uname -a
  
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      lastname: "khor"
    steps:
      - name: step1
        run: |
          echo "$greetings! from $name $lastname"
          echo "${{vars.app_name}} is hosted on ${{vars.SERVER_NAME}}"
        env:
          name: cf
      - name: step2 for testing
        run: |
          cat /etc/os-release 
          hostname
          touch /tmp/cf
          echo "$greetings! from $name"
      
  
